package com.example.user.myapplication.dao;

import com.example.user.myapplication.dao.EventDAO;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eventDAODaoConfig;

    private final EventDAODao eventDAODao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eventDAODaoConfig = daoConfigMap.get(EventDAODao.class).clone();
        eventDAODaoConfig.initIdentityScope(type);

        eventDAODao = new EventDAODao(eventDAODaoConfig, this);

        registerDao(EventDAO.class, eventDAODao);
        registerDao(EventDAO.class, eventDAODao);
    }
    
    public void clear() {
        eventDAODaoConfig.clearIdentityScope();
    }

    public EventDAODao getEventDAODao() {
        return eventDAODao;
    }

}
